# Generated by Django 2.2 on 2019-05-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_space', models.CharField(max_length=255)),
                ('c_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.CharField(blank=True, default='y', max_length=1)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Person')),
            ],
        ),
    ]
