# Generated by Django 2.2 on 2019-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
